### PR TITLE
Make replayer code portable

### PR DESCRIPTION
**Pull request by PoroCYon**
* Exported symbols are now the same (as seen from C) across all (supported) platforms (No leading underscore bullshit)
* `section` syntax differs a bit for NASM ELF output, now fixed.
* More stuff of that ilk

Basically the same procedure as in https://github.com/hzdgopher/4klang/pull/2 , except I was able to test the exporter now as well.

### CODE REVIEW

**Comment by askeksa** [comment]
Thank you for figuring out all the various changes necessary to make the converter and player Linux compatible!

I might want to make some of the changes in a slightly different way, but I will go through them to figure out how they best fit in. I'll probably have some questions along the way...

**Comment by askeksa** [comment]
OK, I finally got around to looking through this PR and trying out the changes, both on Linux (Ubuntu 16.04) and Windows.

I have made several changes from your original proposal, which I will describe in the following. To begin with, I have added the commits (which are still attributed to you) on a branch, so you have a chance to look through them before I merge them to master: https://github.com/askeksa/Oidos/tree/portable_player

So here are the things I changed:
- Various minor changes to macro names and comments.
- Renamed `play.c` to `dump_wav.c` to match the produced executable.
- Section names on Windows are limited to 8 characters, so I changed some of them back and also changed the Windows macros to not add a prefix.
- `nasm` doesn't seem to pre-define symbols identifying the platform, so I changed the platform switch in `platform.inc` to `%ifidn __OUTPUT_FORMAT__, win32` as suggested by the `nasm` manual.
- Defining `ID3D11Texture2D_ID` as a `uint32_t` array does not work with D3D11 code, which must have it as `GUID`, so I changed that back. Since it is guarded by `#ifdef GUID_DEFINED`, it should not disturb other platforms.
- In `random.asm`, I simply define and export both the undecorated and decorated versions of `ID3D11Texture2D_ID` instead of having it depend on the platform.
- I left out the renames of the conversion scripts. While I do realize that Linux conventionally uses all lowercase for files like this, it is not something that blocks them from being used, so for a cross-platform distribution, I prefer to leave them as they are. This also avoids breaking existing scripts.
- `OidosUpgrade.py` is just an internal script for converting pre-2.0 Oidos songs (of which there exist none which haven't already been converted), so there is not much point in maintaining it. Therefore, I left out that change.
- For the `easy_elf` feature, I merged it into `easy_exe`, so there's just one directory, now with an extra script in it. I also rewrote the script to work similarly to the Windows script (i.e. use a `temp` dir, delete temp files before rather than after).
- The last commit was merged into the first one, so we just use `_WIN32` right away.

Do these changes seem reasonable to you?

**Comment by PoroCYon** [comment]
Yup, that all looks fine, no objections from me.

**Comment by askeksa** [comment]
Great. Thanks again for your contribution.

**Pull request closed without merging**
